### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mysterybear** [gcanti/parser-ts#49]
```ts
import { pipe } from "fp-ts/lib/function"
import { char, digit, oneOf } from "parser-ts/lib/char"
import { run } from "parser-ts/lib/code-frame"
import {
  between,
  bind,
  bindTo,
  many,
  optional,
  Parser,
} from "parser-ts/lib/Parser"

const opP = oneOf("+*")

const exprP = pipe(
  digit,
  bindTo("digitLeft"),
  bind("op", () => opP),
  bind("digitRight", () => digit)
)

const maybeWithParenths = <T extends unknown>(p: Parser<string, T>) =>
  optional(between(char("("), char(")"))(p))

const mainP = many(maybeWithParenths(exprP))

const result = run(mainP, "(2+2)(3*3)")

console.log(result)
```

Am I doing something wrong or is this a bug?

**Comment by IMax153** [comment]
This looks like an infinite recursion issue likely resulting from the `many` combinator. Basically what is happening in this particular case is that when the end of the input string is reached (i.e. when both expressions have been parsed), `many` will again enter the `maybeWithParenths` `Parser` and the `optional` combinator will succeed with `None` infinitely since the semantics of `optional` are that the target expression can either be there (i.e. `Some` is returned) or it can not be there (i.e. `None` will be returned). Thus, the `optional` `Parser` will always succeed, causing `many` to iterate infinitely.

Indeed, if I provide the `manyWithParenths` `Parser` with out `many` some sort of terminator to look for by swapping `many` with `manyTill`, everything works.

```typescript
import { pipe } from "fp-ts/lib/function";
import { char, digit, oneOf } from "parser-ts/lib/char";
import { run } from "parser-ts/lib/code-frame";
import {
  between,
  bind,
  bindTo,
  eof,
  manyTill,
  optional,
  Parser
} from "parser-ts/lib/Parser";

const opP = oneOf("+*");

const exprP = pipe(
  digit,
  bindTo("digitLeft"),
  bind("op", () => opP),
  bind("digitRight", () => digit)
);

const maybeWithParenths = <T extends unknown>(p: Parser<string, T>) =>
  optional(between(char("("), char(")"))(p));

const mainP = manyTill(maybeWithParenths(exprP), eof<string>());

const result = run(mainP, "(2+2)(3*3)");

console.log(result);
```
I guess the question here is why do you need to use `optional`? Are you trying to utilize it to handle the end of the input `Stream` of tokens? Because in that case, you will probably want to use `eof` instead.

**Comment by mysterybear** [comment]
Wonderful, thanks!
